# Generated by Django 6.0.4 on 2026-05-01 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='contractor',
            field=models.ForeignKey(limit_choices_to={'role': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='availability_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='bookings.availabilityslot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='contractor',
            field=models.ForeignKey(limit_choices_to={'role': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_contractor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='homeowner',
            field=models.ForeignKey(limit_choices_to={'role': 'homeowner'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_homeowner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='slot_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['homeowner', 'status'], name='bookings_homeown_87d622_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['contractor', 'status'], name='bookings_contrac_5445c4_idx'),
        ),
    ]
