# Generated by Django 6.0.4 on 2026-05-01 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('general', 'General Contractor'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('landscaping', 'Landscaping'), ('roofing', 'Roofing'), ('hvac', 'HVAC'), ('masonry', 'Masonry'), ('interior_design', 'Interior Design'), ('other', 'Other')], default='general', max_length=50)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('insurance_info', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contractor Profile',
                'verbose_name_plural': 'Contractor Profiles',
                'db_table': 'contractor_profiles',
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'portfolio_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General Contractor'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('landscaping', 'Landscaping'), ('roofing', 'Roofing'), ('hvac', 'HVAC'), ('masonry', 'Masonry'), ('interior_design', 'Interior Design'), ('other', 'Other')], default='general', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('project_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'portfolio_projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
