# Generated by Django 6.0.4 on 2026-05-01 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designtemplate',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designimage',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='designs.designtemplate'),
        ),
        migrations.AddField(
            model_name='saveddesign',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='designs.designtemplate'),
        ),
        migrations.AddField(
            model_name='saveddesign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='saveddesign',
            unique_together={('user', 'design')},
        ),
    ]
